### ISSUE TITLE
INT1 using single click

### ISSUE THREAD

**Issue by DylanGWork** [STMicroelectronics/lis2dh12-pid#2]
Hi,

I am trying to setup INT1 to be activated when a single click is detected. There doesn't appear to be a clear explanation on how to route the single click interrupt logic to setting the INT1 pin high.

Could someone please explain how I can use the CLICK_CFG so that it sets off INT1?

Cheers,
Dylan

**Comment by avisconti** [comment]
@DylanGWork 
Sorry for late answer.
Have you tried to take a look to AN5005?
https://www.st.com/resource/en/application_note/an5005-lis2dh12-mems-digital-output-motion-sensor-ultralowpower-highperformance-3axis-nano-accelerometer-stmicroelectronics.pdf

**Comment by Tarast789** [comment]
The same problem - single-click interrupt does not work.
